In [1]:
#pracujemy na tej liście
l = [1,[2,[3,4],5],6,7,[8],9,10,[11,12,[13,14],15],16,[17,18,[[19,20,21,22,23],24],[25,26],27],28]

In [3]:
# poniżej, ponieważ mam się dostać do wartości, a trudno jest wyszukiwać po nawiasach, 
#po prostu kazałem mu wymienić elementy listy od 0 do size
size = len(l)
l[0:size]

[1,
 [2, [3, 4], 5],
 6,
 7,
 [8],
 9,
 10,
 [11, 12, [13, 14], 15],
 16,
 [17, 18, [[19, 20, 21, 22, 23], 24], [25, 26], 27],
 28]

In [47]:
#Dostań się do podanej lub podanych wartości przez indeksowanie
# 5
l[1][2]

5

In [6]:
# 4
l[1][1][1]

4

In [49]:
# 10 
#a tutaj inaczej, ponieważ nie chciało mi się liczyć, który to :). 
#Ale mam problem następujący - przeszukiwanie List pierwszego poziomu w liście potrafię zrobić, 
#ale drugi mi nie wychodzi jakoś...
findPos10=l.index(10import numpy as np)
l[findPos10]

10

In [10]:
# [[2, [3, 4], 5], 6, 7, [8]]
l[1:5]

[[2, [3, 4], 5], 6, 7, [8]]

In [14]:
# [11, [13, 14]]
l[-4][0],l[-4][2]

(11, [13, 14])

In [19]:
# 24
l[-2][2][-1]

24

In [26]:
# 8
l[4]

[8]

In [38]:
# [23, 22, 21, 20, 19]
#tutaj niestety nie wiem jak podać te wartości razem i odwrotnie. Coś w stylu l[-2][-3][-2][-1:-5] nie działa.
l[-2][-3][-2][-1], l[-2][-3][-2][-2], l[-2][-3][-2][-3], l[-2][-3][-2][-4], l[-2][-3][-2][-5]

(23, 22, 21, 20, 19)

In [41]:
#znajdź funkcję, która służy do łączenia ścieżek;
#połącz folder, w którym obecnie pracujesz (wykorzystaj do tego odpowiednią funkcję)
#z folderem o nazwie 'Tygrysek_Kazimierz'. Wynik tego zapisz w zmiennej kazio. Wydrukuj zmienną kazio.
import os
myDir = os.getcwd()
type(myDir)
os.path.join(myDir, 'Tygrysek_Kazimierz')
kazio = os.path.join(myDir, 'Tygrysek_Kazimierz')
print(kazio)
os.makedirs(kazio)

N:\python_anaconda\PD2\Tygrysek_Kazimierz


In [45]:
#korzystając z pewnej nieodgadnionej funkcji,
#podziel zmienną kazio tak, aby każdy kolejny folder był oddzielnym elementem na liście. Zapisz to jako kazio2.
#wybierz z tak stworzonej listy nazwę użytkownika.
path = os.path.normpath(kazio)
kazio1 = path.split(os.sep)
#nie mam nazwy użytkownika w folderze, więc niech będzie nia "python anaconda"
kazio1[1]


'python_anaconda'

In [2]:
import numpy as np
#wektor ar
ar = np.array([1,2,-3,6,7,-10,88,43,-98,17,39,45])
#doklej do wektora ar wartości [4,5,9,10,23,-14,55,13]
ar1= np.array([4,5,9,10,23,-14,55,13])
ar2= np.append(ar,ar1)
ar2

array([  1,   2,  -3,   6,   7, -10,  88,  43, -98,  17,  39,  45,   4,
         5,   9,  10,  23, -14,  55,  13])

In [3]:
#znajdz index dla wartości 9 - użyj odpowiedniej funkcji
#tego nie wiem, tzn zrobiłem, ale nie wiem jak wykorzystać tę informację (array([2], dtype=int64),)
itemindex = np.where(ar2==-3)
print(itemindex)

(array([2], dtype=int64),)


In [4]:
#znajdź indeksy dla wartości mniejszych od zera - użyj odpowiedniej funkcji
itemindex = np.where(ar2<0)
print(itemindex)

(array([ 2,  5,  8, 17], dtype=int64),)


In [5]:
#wyświetl wartości mniejsze od zera
ar2[ar2<0]

array([ -3, -10, -98, -14])

In [6]:
#policz średnią, zaokrąglij do jednego miejsca po przecinku
np.round(np.mean(ar),1)

11.4

In [10]:
#stwórz zmienną ar_abs, wektor wartości bezwględnych z wektora ar
ar_abs_0 = [x*x for x in ar2]
ar_abs = [x**(0.5) for x in ar_abs_0]
ar_abs

[1.0,
 2.0,
 3.0,
 6.0,
 7.0,
 10.0,
 88.0,
 43.0,
 98.0,
 17.0,
 39.0,
 45.0,
 4.0,
 5.0,
 9.0,
 10.0,
 23.0,
 14.0,
 55.0,
 13.0]

In [11]:
#stwórz zmienną ar_p, wektor pierwiastków trzeciego stopnia z wektora ar
#mam jednak problem z pierwiastkiem 3-go stopnia z liczb ujemnych :). Dlatego - sorry, je pomijam :)
#było tak ar_abs = [x**(1/3) for x in ar2 if x>0]
ar_p = [x**(1/3) for x in ar_abs]
print(ar_p)

[1.0, 1.2599210498948732, 1.4422495703074083, 1.8171205928321397, 1.9129311827723889, 2.1544346900318838, 4.4479601811386305, 3.5033980603867239, 4.6104362920584459, 2.5712815906582351, 3.3912114430141664, 3.5568933044900626, 1.5874010519681994, 1.7099759466766968, 2.0800838230519041, 2.1544346900318838, 2.8438669798515654, 2.4101422641752297, 3.8029524607613912, 2.3513346877207573]


In [12]:
#zaokrąglij wektor ar_p do dwóch miejsc po przecinku
np.round(ar_p,2)

array([ 1.  ,  1.26,  1.44,  1.82,  1.91,  2.15,  4.45,  3.5 ,  4.61,
        2.57,  3.39,  3.56,  1.59,  1.71,  2.08,  2.15,  2.84,  2.41,
        3.8 ,  2.35])

In [16]:
#zsumuj zaokrąglony wektor ar_p i podnieś go do kwadratu, 
#zmienną nazwij ar_sq, zmień typ tej zmiennej na liczbę całkowitą
np.sum(ar_p)
ar_są=np.sum(ar_p)
ar_są=ar_są*ar_są
print(ar_są)
ar_są=int(ar_są)
type(ar_są)

2561.1726865


int

In [14]:
#moje_notatki
sqrt = [x*x for x in ar2]
print(sqrt)

[1, 4, 9, 36, 49, 100, 7744, 1849, 9604, 289, 1521, 2025, 16, 25, 81, 100, 529, 196, 3025, 169]


In [15]:
#moje notatki
import math
-math.pow(3, float(1)/3)

-1.4422495703074083